# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image:
  repository: ghcr.io/andrey-ilin/kbot
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
<<<<<<< Updated upstream
  tag: "v1.0.6-3dfc90b"
=======
  tag: "v1.0.6-59c5f10"
  os: linux
>>>>>>> Stashed changes
  arch: amd64
secret:
  name: "kbot"
  env: "TELE_TOKEN"
  key: "token"
securityContext:
  privileged: true
