# Name of Pipeline
name: KBOT-CICD

# Triger event
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

# Declare Jobs on Ubuntu latest VM
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full Git history is fetched to get tags

      - name: Set VERSION variable
        run: echo "VERSION=$(git describe --tags --abbrev=0)-$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Run test
        run: make test

      - name: Build and Push image to ghcr.io
        run: |
          docker login ghcr.io --username ${{ vars.GH_REGISTERY_USERNAME }} --password ${{ secrets.GH_REGISTRY_TOKEN }}
          make imageGithubCloud VERSION="$VERSION"
          make pushGithubCloudRegistery VERSION="$VERSION"
        env:
          VERSION: ${{ env.VERSION }}  # Use the VERSION variable